# This is a basic workflow that is manually triggered

name: deneme

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
   workflow_run:
      workflows: manual
      branches: main
      types: completed
   workflow_dispatch:
    inputs:
      revisionKey:
        description: 'Commit hash(first 7 char):'
        required: false
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    name: ${{ github.ref_name }} deploying - ${{ github.event.inputs.revisionKey || ${github.sha} | cut -c1-7) }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    - name: Step
      run: echo ${GITHUB_SHA::7}
