# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  
    - name: scheck steps 
      run: echo "${{ github.event.workflow_run.head_sha }}"
    - name: Build image for commit
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: ${{ steps.commit.outputs.short }}
    - name: print hash
      run: echo COMMIT_HASH.slice(0, 7)
    - name: Check outputs
      run: echo |
        ${{ steps.vars.outputs.sha_short }}
        "::set-output name=sha_short::$(git rev-parse --short ${{ github.event.pull_request.head.sha }})"
    - name: Step
      run: echo ${GITHUB_SHA::7}
